[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'y-yamagata/ezbuffer.vim'
hook_add = '''
    nnoremap <silent>eb :EzBuffer<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_min_cache_files = 256
    "nnoremap <silent><BS><BS> :VimFiler<CR>
    nnoremap <silent><BS><BS> :VimFiler -winwidth=40 -split -direction=topleft -toggle -simple -no-quit<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
    let g:unite_enable_start_insert = 1
    let g:unite_source_file_mru_limit = 50
    let g:unite_source_file_mru_filename_format = ''
    nnoremap [unite] <Nop>
    nmap <Space>u [unite]
    nnoremap <silent> [unite]b :<C-u>Unite -winheight=15 buffer<CR>
    nnoremap <silent> [unite]r :<C-u>Unite -winheight=15 -buffer-name=register register<CR>
    nnoremap <silent> [unite]m :<C-u>Unite -winheight=15 file_mru<CR>
    autocmd FileType unite call s:unite_my_settings()
    function! s:unite_my_settings() abort
        nmap <buffer> <ESC> <Plug>(unite_exit)
    endfunction
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
    let g:syntastic_swift_checkers = ['swiftlint']
    if isdirectory(getcwd() . '/src/main/java')
        let g:syntastic_java_javac_classpath = getcwd() . '/src/main/java'
    endif
    let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'
'''

[[plugins]]
repo = 'keith/swift.vim'
